language: java

jdk:
  - oraclejdk8


branches:
  only:
    - master
before_install:
  - cd application
  - chmod +x gradlew

script:
  - ./gradlew build


cache:
  directories:
  - D:/Лабы(2курс)/СУБД/Lab3_db/.gradle

